version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-stretch-node-browsers
    steps:
      - type: shell
        shell: /bin/sh
        pwd: /
        command: sudo apt update && sudo apt install git -y && git --version

      # Update environment
      - run: sudo apt update

      # Install rsync. It will be used to upload our code to server
      - run: sudo apt-get install rsync
      - run: apt-get install python3-pip


      # Sync the SSH keys 
      - add_ssh_keys

      # Check out the code in the project directory
      - checkout
      - run: sudo pip install -r requirements.txt
      - run: sudo pip install pytest
      - run: pytest

      # Add the server to known hosts
      - run: ssh-keyscan -H 161.97.74.5 >> ~/.ssh/known_hosts

      # Finally, upload your files to server.
      - run: rsync -avce ssh --delete ./ root@161.97.74.5:/root/data_parachuting/circle_ci_test
