version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-stretch-node-browsers
    steps:
      - type: shell
        shell: /bin/sh
        pwd: /
        command: sudo apt update && sudo apt install git -y && git --version

      # Update environment
      - run: sudo apt update

      # Install rsync. It will be used to upload our code to server
      - run: sudo apt-get install rsync

      # Sync the SSH keys 
      - add_ssh_keys

      # Check out the code in the project directory
      - checkout
      - run: sudo apt-get install python3-pip
      - run: python3 -m pip install --upgrade pip
      - run: sudo python3 -m pip install -r requirements.txt
      - run: pytest -v


      # Add the server to known hosts
      - run: ssh-keyscan -H 161.97.74.5 >> ~/.ssh/known_hosts
      - run: ssh-keyscan -H 143.47.242.29 >> ~/.ssh/known_hosts

      # Finally, upload your files to server.
      - run: rsync -avce ssh --delete ./ root@${{ secrets.REMOTE_HOST }}:/root/data_parachuting/circle_ci_test
      - run: rsync -avce ssh --delete ./ ubuntu@143.47.242.29:/home/ubuntu/data_parachuting/circle_ci_test
